name       : stk
version    : 4.6.1
release    : 7
source     :
    - https://ccrma.stanford.edu/software/stk/release/stk-4.6.1.tar.gz : e77ba3c80cdd93ca02c34098b9b7f918df3d648c87f1ed5d94fe854debd6d101
license    : MIT # With some special useless clause, check their LICENSE.
component  : multimedia.library
summary    : Audio signal processing and algorithmic synthesis classes written in
    C++
description: |
    The Synthesis ToolKit in C++ (STK) is a set of open source audio signal processing and algorithmic synthesis classes written in the C++ programming language. STK was designed to facilitate rapid development of music synthesis and audio processing software, with an emphasis on cross-platform functionality, realtime control, ease of use, and educational example code. The Synthesis ToolKit is extremely portable (it's mostly platform-independent C and C++ code), and it's completely user-extensible (all source included, no unusual libraries, and no hidden drivers).
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(jack)
setup      : |
    %configure RAWWAVE_PATH=/usr/share/${pkgname}/rawwaves/ \
               --libdir=/lib%LIBSUFFIX% \
               --enable-shared \
               --with-alsa \
               --with-jack
build      : |
    %make
install    : |
    %make_install
    install -Dm0644 rawwaves/*.{raw,c} -t $installdir/usr/share/stk/rawwaves
patterns   :
    - /usr/lib64/lib*.so
