name       : stk
version    : 4.5.1
release    : 4
source     :
    - http://ccrma.stanford.edu/software/stk/release/stk-4.5.1.tar.gz : 3466860901a181120d3bd0407e4aeb5ab24127a4350c314af106778c1db88594
license    : MIT # With some special useless clause, check their LICENSE.
component  : multimedia.library
summary    : Audio signal processing and algorithmic synthesis classes written in
    C++
description: |
    The Synthesis ToolKit in C++ (STK) is a set of open source audio signal processing and algorithmic synthesis classes written in the C++ programming language. STK was designed to facilitate rapid development of music synthesis and audio processing software, with an emphasis on cross-platform functionality, realtime control, ease of use, and educational example code. The Synthesis ToolKit is extremely portable (it's mostly platform-independent C and C++ code), and it's completely user-extensible (all source included, no unusual libraries, and no hidden drivers).
builddeps  :
    - pkgconfig(alsa)
setup      : |
    %configure --libdir=/lib%LIBSUFFIX%
build      : |
    %make
install    : |
    %make_install
patterns   :
    - /usr/lib64/lib*.so
